### PR TITLE
Remove the useless code

### PR DESCRIPTION
**Pull request by TheRockettek**
Why do you even need that, i just want to 8 ball in peace.

### CODE REVIEW

**Comment by bsoyka** [comment]
The `sentry_sdk` code is implemented to report errors back to me so that I am able to diagnose them and fix them for everyone, and I don’t have to worry about users not reporting issues by themselves.  Whenever there is any kind of error thrown, I get an email and can see how many users have encountered the same error.

**Comment by bsoyka** [comment]
It shouldn’t have any effect on regular users, as they have the same experience as they would without it, but when they encounter an error, I can solve it and improve the program.

**Comment by bsoyka** [comment]
In fact, with some of these errors, I add them as GitHub issues.  I’m guessing #53 and #54 were caused when you played around in the code.

**Comment by TheRockettek** [comment]
But how would it even break, its just random.choice from a list. Its not necessary and wont break...

**Comment by bsoyka** [comment]
I agree, it is fairly simple, however Sentry is used.  Thanks for the PR, but I would like to keep Sentry installed on this program.  Have a great day.

**Pull request closed without merging**
