### PR TITLE
Add parameter to function and change function name

### LINKED ISSUE #3: Allow programmatic question input
Make a parameter in the main function, maybe change the function’s name.

### PR DESCRIPTION
**Pull request by ghost**
Closes #3

### CODE REVIEW

**Review by bsoyka — CHANGES_REQUESTED** [review]
Can you wrap lines 30-35 in the following if statement?
`if __name__ == “__main__”:`
Thanks!  I just don’t want those lines to run when they’re not supposed to.

**Comment by mbuccat** [comment]
Ok, will do

**Review by bsoyka — APPROVED** [review]

**Comment by bsoyka** [comment]
This looks great, thanks for the help, @mbuccat!

**Comment by bsoyka** [comment]
@mbuccat I hope you’re feeling better with Git and Hacktoberfest!

**Pull request merged**
